### ISSUE TITLE
Uncompleted enum in Minimum Viable Record does not block form submission

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/treecreeper#195]
To recreate

Add the following to `example-schema/types/MVRType.yaml`

```yaml
  someEnum:
    type: AnEnum
    description: Word description.
    label: Word label
    useInSummary: true
```

Open http://local.in.ft.com:8888/MVRType/create and complete all fields except the enum

Expected: Get an alert and the form won't submit
Actual behaviour: Form submits ok
