### ISSUE TITLE
Support showing filtered relationship in the UI

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/treecreeper#202]
e.g. this gets repositories, filtered to only those which have admin rights 

```
  ownedRepositories:
    type: Repository
    label: Owned repositories
    description: Repositories this team has admin access to
    hasMany: true
    cypher: MATCH (this)-[rel:HAS_ACCESS_TO]->(repo) WHERE rel.role = 'ADMIN' RETURN repo
```

Is there a better way that might work, e.g. allowing defining a default filter condition on the property:

```
   filter: "{role: ADMIN}"
   filterDescription: Repositories the team has admin rights to
```

UI shows message `filtered to only show ${message}` with show all button

Oh, so complex
